plugins {
    id 'multiloader-common'
    id 'fabric-loom'
}

sourceSets {
    main {
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation(project(':fabric')) {
        capabilities {
            requireCapability "$group:$mod_id-fabric"
        }
    }

    compileOnly(project(':testmod-common')) {
        capabilities {
            requireCapability "$group:$mod_id-testmod-common"
        }
    }
}

// Pull in the testmod-common sources
configurations {
    testmodCommonJava { canBeResolved = true }
    testmodCommonResources { canBeResolved = true }
}

dependencies {
    testmodCommonJava project(path: ':testmod-common', configuration: 'testmodCommonJava')
    testmodCommonResources project(path: ':testmod-common', configuration: 'testmodCommonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.testmodCommonJava)
    source(configurations.testmodCommonJava)
}

processResources {
    dependsOn(configurations.testmodCommonResources)
    from(configurations.testmodCommonResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.testmodCommonJava)
    from(configurations.testmodCommonJava)
    dependsOn(configurations.testmodCommonResources)
    from(configurations.testmodCommonResources)
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client (Testmod)')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server (Testmod)')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}