modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "uilib"
version = "${version}"
displayName = "UI Lib"
authors = "DAQEM"
description = '''
A user interface library for Minecarft modding.
'''
#logoFile = ""

[[dependencies.uilib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uilib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uilib]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"