plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', "${mod_id}_testmod")
            ideName = "NeoForge ${it.name.capitalize()} (Testmod) (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}_testmod" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation(project(':neoforge')) {
        capabilities {
            requireCapability "$group:$mod_id-neoforge"
        }
    }

    compileOnly(project(':testmod-common')) {
        capabilities {
            requireCapability "$group:$mod_id-testmod-common"
        }
    }
}

// Pull in the testmod-common sources
configurations {
    testmodCommonJava { canBeResolved = true }
    testmodCommonResources { canBeResolved = true }
}

dependencies {
    testmodCommonJava project(path: ':testmod-common', configuration: 'testmodCommonJava')
    testmodCommonResources project(path: ':testmod-common', configuration: 'testmodCommonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.testmodCommonJava)
    source(configurations.testmodCommonJava)
}

processResources {
    dependsOn(configurations.testmodCommonResources)
    from(configurations.testmodCommonResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.testmodCommonJava)
    from(configurations.testmodCommonJava)
    dependsOn(configurations.testmodCommonResources)
    from(configurations.testmodCommonResources)
}