name: Run Tests

on:
  push:
    branches: [ "1.20.1-dev" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    
    runs-on: ubuntu-latest

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
        
      - name: Test
        run: ./gradlew :common:test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            common/build/test-results/**/*.xml
